//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ban
    {
        public int id { get; set; }
        public int random { get; set; }
        public string dictionary { get; set; }
        public string text { get; set; }
        public string cc { get; set; }
        public string dxp { get; set; }
        public Nullable<int> ndoc { get; set; }
        public string xml { get; set; }
        public string extra { get; set; }
    }
}
