//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.Iter
{
    	using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
    
    public partial class labels : EntityBase
    	{		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    		public labels()
    		{		}
    
    			private int _id;
    	public int id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    		private string _tipolabel_tipo;
    	public string tipolabel_tipo 
    	{ 
    		get { return _tipolabel_tipo; } 
    		set { SetProperty(ref _tipolabel_tipo, value); } 
    	}
    		private string _value;
    	public string value 
    	{ 
    		get { return _value; } 
    		set { SetProperty(ref _value, value); } 
    	}
    		private Nullable<bool> _main;
    	public Nullable<bool> main 
    	{ 
    		get { return _main; } 
    		set { SetProperty(ref _main, value); } 
    	}
    		private int _iter_id;
    	public int iter_id 
    	{ 
    		get { return _iter_id; } 
    		set { SetProperty(ref _iter_id, value); } 
    	}
    		private int _rowversion;
    	public int rowversion 
    	{ 
    		get { return _rowversion; } 
    		set { SetProperty(ref _rowversion, value); } 
    	}
    
    		public virtual tipolabel tipolabel { get; set; }	}
}
