//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.Iter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NiterEntities2 : DbContext
    {
        public NiterEntities2()
            : base("name=NiterEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<labels> labels { get; set; }
        public virtual DbSet<tipolabel> tipolabel { get; set; }
        public virtual DbSet<log> log { get; set; }
    }
}
