//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF2.db.model1
{
    
    using System;
    using System.ComponentModel.DataAnnotations;
	using xwcs.core.db;
    
    // This class is just for meta attributes editing
    // Do not write any logic here, it will be not considered
    // Copy this class somewhere else this one will be overridden!!!
    
    public class bab_meta
    {
		const string MainGroup = "{tabs}";
		const string Resp = MainGroup + "/Responsabilita";
		const string MG_Main = MainGroup + "/<Doc>/Main";
		const string MG_Parole = MainGroup + "/<Doc>/Parole";
		const string MG_Testo = MainGroup + "/<Doc>/Testo";

		[Display(Name = "n° Doc", GroupName = MG_Main + "/<IdRandom->", Order = 1)]
		[System.ComponentModel.ReadOnly(true)]
		[xwcs.core.db.binding.attributes.Style(BackgrounColor = 0xFFADFF2F)]
		public int ndoc { get; set; }

		[xwcs.core.db.binding.attributes.Style(BackgrounColor = 0xFFADFF2F)]
		[Display(Name = "Id", GroupName = MG_Main + "/<IdRandom->")]
		[System.ComponentModel.ReadOnly(true)]
		[xwcs.core.db.binding.attributes.Style(BackgrounColor = 0xFFADFF2F)]
		public int id { get; set; }

		[xwcs.core.db.binding.attributes.Style(BackgrounColor = 0xFFADFF2F)]
		[Display(Name = "Random", GroupName = MG_Main + "/<IdRandom->")]
		[Range(0, 1000, ErrorMessage = "Fuori range!")]
		public int random { get; set; }
		[Display(Name = "Parole", GroupName = MG_Parole)]
		public string dictionary { get; set; }
		[Display(Name = "Testo", GroupName = MG_Parole), DataType(DataType.MultilineText)]
		public string text { get; set; }
		[Display(Name = "RPA", GroupName = Resp)]
		public string rpa { get; set; }
		[Display(Name = "CC", GroupName = Resp)]
		[xwcs.core.db.binding.attributes.DbLookupAttribute(DisplayMember = "Name", ValueMember = "Name")]
		public string cc { get; set; }
		[Display(Name = "DXP", GroupName = Resp)]
		public string dxp { get; set; }
		[System.ComponentModel.ReadOnly(true)]
		[Display(Name = "xml", GroupName = MainGroup + "/XML"), DataType(DataType.MultilineText)]
		public string xml { get; set; }
		[Display(AutoGenerateField = false)]
		public string extra { get; set; }

		[Display(Name="Content_dump_xml", GroupName = MG_Parole), DataType(DataType.MultilineText)]
    	public string content_dump_xml { get; set;}
    
    	[Display(Name="Content_dump_xml_obj", GroupName = "{tabs}/Embeded", Order = 4)]
		public object content_dump_xml_obj { get; set;}
    
    
    	[Display(AutoGenerateField=false)]
        public virtual bab_local bab_local { get; set; }
    }


	public class bab_ext : EntityBase
	{
		public const UInt32 greenColor = 0xff008000;

		[xwcs.core.db.binding.attributes.Style(BackgrounColor = greenColor)]
		[Display(Name = "N_RPA", GroupName = "n")]
		public string n_rpa { get; set; }
		[Display(Name = "N_CC", GroupName = "n"), Required()]
		public string n_cc { get; set; }
		[xwcs.core.db.binding.attributes.Style(BackgrounColor = greenColor)]
		[Display(Name = "N_DXP", GroupName = "n"), DataType(DataType.MultilineText)]
		public string n_dxp { get; set; }
		[xwcs.core.db.binding.attributes.Style(BackgrounColor = 0xFFADFF2F)]
		[Display(Name = "N_Date", GroupName = "n")]
		public DateTime n_data { get; set; }
	}


	public class bab_ext_1 : EntityBase
	{
		public const UInt32 greenColor = 0xff008000;

		[xwcs.core.db.binding.attributes.Style(BackgrounColor = greenColor)]
		[Display(Name = "N_RPA", GroupName = "n")]
		public string n_rpa { get; set; }
		[Display(Name = "N_CC", GroupName = "n")]
		public string n_cc { get; set; }
		[xwcs.core.db.binding.attributes.Style(BackgrounColor = greenColor)]
		[Display(Name = "N_DXP", GroupName = "n")]
		public string n_dxp { get; set; }
	}

	// This class couple its entity and it should be use
	// for extending functionalities of Entity class
	// here can be add de-serialized complex fields
	// or other necessary logic
	// copy this class to some other place
	// changes in this place will be overridden !!!

	[MetadataType(typeof(bab_meta))]
    public partial class bab
    {
    	
    }
    
}
