//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF2.db.model1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
    
    public partial class ban : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ban()
        {
    
    	}
    
    	    private int _id;
    	public int id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
        private int _random;
    	public int random 
    	{ 
    		get { return _random; } 
    		set { SetProperty(ref _random, value); } 
    	}
    
        private string _dictionary;
    	public string dictionary 
    	{ 
    		get { return _dictionary; } 
    		set { SetProperty(ref _dictionary, value); } 
    	}
    
        private string _text;
    	public string text 
    	{ 
    		get { return _text; } 
    		set { SetProperty(ref _text, value); } 
    	}
    
        private string _cc;
    	public string cc 
    	{ 
    		get { return _cc; } 
    		set { SetProperty(ref _cc, value); } 
    	}
    
        private string _dxp;
    	public string dxp 
    	{ 
    		get { return _dxp; } 
    		set { SetProperty(ref _dxp, value); } 
    	}
    
        private Nullable<int> _ndoc;
    	public Nullable<int> ndoc 
    	{ 
    		get { return _ndoc; } 
    		set { SetProperty(ref _ndoc, value); } 
    	}
    
        private string _xml;
    	public string xml 
    	{ 
    		get { return _xml; } 
    		set { SetProperty(ref _xml, value); } 
    	}
    
        private string _extra;
    	public string extra 
    	{ 
    		get { return _extra; } 
    		set { SetProperty(ref _extra, value); } 
    	}
    
    
    }
}
