//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.model1
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    
    // This class is just for meta attributes editing
    // Do not write any logic here, it will be not considered
    // Copy this class somewhere else this one will be overridden!!!
    
    public class bar_data_meta
    {
        [Display(Name="Id")]
    		public int id { get; set;}
    
        [Display(Name="Dictionary")]
    		public string dictionary { get; set;}
    
        [Display(Name="Text")]
    		public string text { get; set;}
    
    }
    
    
    // This class couple its entity and it should be use
    // for extending functionalities of Entity class
    // here can be add de-serialized complex fields
    // or other necessary logic
    // copy this class to some other place
    // changes in this place will be overridden !!!
    
    [MetadataType(typeof(bar_data_meta))]
    public partial class bar_data
    {
    	// example of de-serialized polymorph filed
    	//[PolymorphFlag(Kind = PolymorphKind.XmlSerialization, SourcePropertyName = "<some_field>")]
    	//public object some_field_object { get; set; } = null;
    }
    
}
