//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.model1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
    
    public partial class bar_data : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bar_data()
        {
    
    	}
    
    	    private int _id;
    	public int id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
        private string _dictionary;
    	public string dictionary 
    	{ 
    		get { return _dictionary; } 
    		set { SetProperty(ref _dictionary, value); } 
    	}
    
        private string _text;
    	public string text 
    	{ 
    		get { return _text; } 
    		set { SetProperty(ref _text, value); } 
    	}
    
    
    }
}
