//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.iter_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
    
    public partial class iter : EntityBase
    {
    	#region ctors and defaults
    
    	public iter() 
    	{
    	}
    	
    	
    	#endregion
    
    	#region properties
    	private long _id;
    	public long id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	private long _nrecord;
    	public long nrecord 
    	{ 
    		get { return _nrecord; } 
    		set { SetProperty(ref _nrecord, value); } 
    	}
    
    	private long _ncopia;
    	public long ncopia 
    	{ 
    		get { return _ncopia; } 
    		set { SetProperty(ref _ncopia, value); } 
    	}
    
    	private string _versione;
    	public string versione 
    	{ 
    		get { return _versione; } 
    		set { SetProperty(ref _versione, value); } 
    	}
    
    	private long _build;
    	public long build 
    	{ 
    		get { return _build; } 
    		set { SetProperty(ref _build, value); } 
    	}
    
    	private long _id_tipologie;
    	public long id_tipologie 
    	{ 
    		get { return _id_tipologie; } 
    		set { SetProperty(ref _id_tipologie, value); } 
    	}
    
    	private string _tipi_tipo;
    	public string tipi_tipo 
    	{ 
    		get { return _tipi_tipo; } 
    		set { SetProperty(ref _tipi_tipo, value); } 
    	}
    
    	private Nullable<System.DateTime> _datadoc;
    	public Nullable<System.DateTime> datadoc 
    	{ 
    		get { return _datadoc; } 
    		set { SetProperty(ref _datadoc, value); } 
    	}
    
    	private Nullable<System.DateTime> _decade;
    	public Nullable<System.DateTime> decade 
    	{ 
    		get { return _decade; } 
    		set { SetProperty(ref _decade, value); } 
    	}
    
    	private string _oTA;
    	public string OTA 
    	{ 
    		get { return _oTA; } 
    		set { SetProperty(ref _oTA, value); } 
    	}
    
    	private string _oggetto_uff;
    	public string oggetto_uff 
    	{ 
    		get { return _oggetto_uff; } 
    		set { SetProperty(ref _oggetto_uff, value); } 
    	}
    
    	private Nullable<System.DateTime> _data;
    	public Nullable<System.DateTime> data 
    	{ 
    		get { return _data; } 
    		set { SetProperty(ref _data, value); } 
    	}
    
    	private string _numero;
    	public string numero 
    	{ 
    		get { return _numero; } 
    		set { SetProperty(ref _numero, value); } 
    	}
    
    	private Nullable<long> _articolo;
    	public Nullable<long> articolo 
    	{ 
    		get { return _articolo; } 
    		set { SetProperty(ref _articolo, value); } 
    	}
    
    	private string _art_estens;
    	public string art_estens 
    	{ 
    		get { return _art_estens; } 
    		set { SetProperty(ref _art_estens, value); } 
    	}
    
    	private string _protocollo;
    	public string protocollo 
    	{ 
    		get { return _protocollo; } 
    		set { SetProperty(ref _protocollo, value); } 
    	}
    
    	private Nullable<long> _id_editori;
    	public Nullable<long> id_editori 
    	{ 
    		get { return _id_editori; } 
    		set { SetProperty(ref _id_editori, value); } 
    	}
    
    	private Nullable<long> _id_fonti;
    	public Nullable<long> id_fonti 
    	{ 
    		get { return _id_fonti; } 
    		set { SetProperty(ref _id_fonti, value); } 
    	}
    
    	private Nullable<System.DateTime> _fonte_data;
    	public Nullable<System.DateTime> fonte_data 
    	{ 
    		get { return _fonte_data; } 
    		set { SetProperty(ref _fonte_data, value); } 
    	}
    
    	private string _fonte_numero;
    	public string fonte_numero 
    	{ 
    		get { return _fonte_numero; } 
    		set { SetProperty(ref _fonte_numero, value); } 
    	}
    
    	private string _viol_gruppo_ipotesi;
    	public string viol_gruppo_ipotesi 
    	{ 
    		get { return _viol_gruppo_ipotesi; } 
    		set { SetProperty(ref _viol_gruppo_ipotesi, value); } 
    	}
    
    	private string _viol_ipotesi;
    	public string viol_ipotesi 
    	{ 
    		get { return _viol_ipotesi; } 
    		set { SetProperty(ref _viol_ipotesi, value); } 
    	}
    
    	private string _viol_norma_violata;
    	public string viol_norma_violata 
    	{ 
    		get { return _viol_norma_violata; } 
    		set { SetProperty(ref _viol_norma_violata, value); } 
    	}
    
    	private string _parte;
    	public string parte 
    	{ 
    		get { return _parte; } 
    		set { SetProperty(ref _parte, value); } 
    	}
    
    	private string _parti_collegate;
    	public string parti_collegate 
    	{ 
    		get { return _parti_collegate; } 
    		set { SetProperty(ref _parti_collegate, value); } 
    	}
    
    	private Nullable<bool> _storico;
    	public Nullable<bool> storico 
    	{ 
    		get { return _storico; } 
    		set { SetProperty(ref _storico, value); } 
    	}
    
    	private string _stati_stato;
    	public string stati_stato 
    	{ 
    		get { return _stati_stato; } 
    		set { SetProperty(ref _stati_stato, value); } 
    	}
    
    	private Nullable<bool> _hide;
    	public Nullable<bool> hide 
    	{ 
    		get { return _hide; } 
    		set { SetProperty(ref _hide, value); } 
    	}
    
    	private string _hide_reason;
    	public string hide_reason 
    	{ 
    		get { return _hide_reason; } 
    		set { SetProperty(ref _hide_reason, value); } 
    	}
    
    	private Nullable<double> _prezzo;
    	public Nullable<double> prezzo 
    	{ 
    		get { return _prezzo; } 
    		set { SetProperty(ref _prezzo, value); } 
    	}
    
    	private Nullable<bool> _prezzoForzato;
    	public Nullable<bool> prezzoForzato 
    	{ 
    		get { return _prezzoForzato; } 
    		set { SetProperty(ref _prezzoForzato, value); } 
    	}
    
    	private Nullable<System.DateTime> _vigenteDa;
    	public Nullable<System.DateTime> vigenteDa 
    	{ 
    		get { return _vigenteDa; } 
    		set { SetProperty(ref _vigenteDa, value); } 
    	}
    
    	private Nullable<System.DateTime> _vigenteA;
    	public Nullable<System.DateTime> vigenteA 
    	{ 
    		get { return _vigenteA; } 
    		set { SetProperty(ref _vigenteA, value); } 
    	}
    
    	private Nullable<System.DateTime> _visibileDa;
    	public Nullable<System.DateTime> visibileDa 
    	{ 
    		get { return _visibileDa; } 
    		set { SetProperty(ref _visibileDa, value); } 
    	}
    
    	private Nullable<System.DateTime> _visibileA;
    	public Nullable<System.DateTime> visibileA 
    	{ 
    		get { return _visibileA; } 
    		set { SetProperty(ref _visibileA, value); } 
    	}
    
    	private Nullable<System.DateTime> _dataAggiornamento;
    	public Nullable<System.DateTime> dataAggiornamento 
    	{ 
    		get { return _dataAggiornamento; } 
    		set { SetProperty(ref _dataAggiornamento, value); } 
    	}
    
    	#endregion
    
    
    	#region navigation
    
    	public virtual tipologie tipologie { get; set; }
    
    	#endregion
    }
}
