//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.iter_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
     
    // This class is just for meta attributes editing
    // Do not write any logic here, it will be not considered
    // Copy this class somewhere else this one will be overridden!!!
    
    public class iter_in_opere_meta
    {
    	#region properties
    
    	[Display(Name="Id")]
    	public long id { get; set;}
    
    	[Display(Name="Nrecord")]
    	public long nrecord { get; set;}
    
    	[Display(Name="Id_opere")]
    	public long id_opere { get; set;}
    
    	[Display(Name="Pagina")]
    	public string pagina { get; set;}
    
    	[Display(Name="Info")]
    	public string info { get; set;}
    
    	[Display(Name="Modificato")]
    	public Nullable<bool> modificato { get; set;}
    
    	[Display(Name="Forzato")]
    	public Nullable<bool> forzato { get; set;}
    
    	[Display(Name="Num_pagine")]
    	public Nullable<int> num_pagine { get; set;}
    
    	#endregion
    
    	#region navigation
    
    	[Display(AutoGenerateField=false)]
    	public virtual opere opere { get; set; }
    
    	#endregion
    }
    
    
    // This class couple its entity and it should be use
    // for extending functionalities of Entity class
    // here can be add de-serialized complex fields
    // or other necessary logic
    // copy this class to some other place
    // changes in this place will be overridden !!!
    
    [MetadataType(typeof(iter_in_opere_meta))]
    public partial class iter_in_opere
    {
    	// custom implementations
    }
}
