//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.iter_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
    
    public partial class iter_in_opere : EntityBase
    {
    	#region ctors and defaults
    
    	public iter_in_opere() 
    	{
    	}
    	
    	
    	#endregion
    
    	#region properties
    	private long _id;
    	public long id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	private long _nrecord;
    	public long nrecord 
    	{ 
    		get { return _nrecord; } 
    		set { SetProperty(ref _nrecord, value); } 
    	}
    
    	private long _id_opere;
    	public long id_opere 
    	{ 
    		get { return _id_opere; } 
    		set { SetProperty(ref _id_opere, value); } 
    	}
    
    	private string _pagina;
    	public string pagina 
    	{ 
    		get { return _pagina; } 
    		set { SetProperty(ref _pagina, value); } 
    	}
    
    	private string _info;
    	public string info 
    	{ 
    		get { return _info; } 
    		set { SetProperty(ref _info, value); } 
    	}
    
    	private Nullable<bool> _modificato;
    	public Nullable<bool> modificato 
    	{ 
    		get { return _modificato; } 
    		set { SetProperty(ref _modificato, value); } 
    	}
    
    	private Nullable<bool> _forzato;
    	public Nullable<bool> forzato 
    	{ 
    		get { return _forzato; } 
    		set { SetProperty(ref _forzato, value); } 
    	}
    
    	private Nullable<int> _num_pagine;
    	public Nullable<int> num_pagine 
    	{ 
    		get { return _num_pagine; } 
    		set { SetProperty(ref _num_pagine, value); } 
    	}
    
    	#endregion
    
    
    	#region navigation
    
    	public virtual opere opere { get; set; }
    
    	#endregion
    }
}
