//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.iter_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
     
    // This class is just for meta attributes editing
    // Do not write any logic here, it will be not considered
    // Copy this class somewhere else this one will be overridden!!!
    
    public class opere_meta
    {
    	#region properties
    
    	[Display(Name="Id")]
    	public long id { get; set;}
    
    	[Display(Name="Descrizione")]
    	public string descrizione { get; set;}
    
    	[Display(Name="Dna_cod_articolo")]
    	public string dna_cod_articolo { get; set;}
    
    	[Display(Name="Usabile_in_iter")]
    	public int usabile_in_iter { get; set;}
    
    	[Display(Name="Disabilitato")]
    	public Nullable<bool> disabilitato { get; set;}
    
    	#endregion
    
    	#region navigation
    
    	[Display(AutoGenerateField=false)]
    	public virtual ICollection<iter_in_opere> iter_in_opere { get; set; }
    
    	#endregion
    }
    
    
    // This class couple its entity and it should be use
    // for extending functionalities of Entity class
    // here can be add de-serialized complex fields
    // or other necessary logic
    // copy this class to some other place
    // changes in this place will be overridden !!!
    
    [MetadataType(typeof(opere_meta))]
    public partial class opere
    {
    	// custom implementations
    }
}
