//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.iter_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
    
    public partial class opere : EntityBase
    {
    	#region ctors and defaults
    
    	public opere() 
    	{
    		this.iter_in_opere = new HashSet<iter_in_opere>();
    	}
    	
    	
    	#endregion
    
    	#region properties
    	private long _id;
    	public long id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	private string _descrizione;
    	public string descrizione 
    	{ 
    		get { return _descrizione; } 
    		set { SetProperty(ref _descrizione, value); } 
    	}
    
    	private string _dna_cod_articolo;
    	public string dna_cod_articolo 
    	{ 
    		get { return _dna_cod_articolo; } 
    		set { SetProperty(ref _dna_cod_articolo, value); } 
    	}
    
    	private int _usabile_in_iter;
    	public int usabile_in_iter 
    	{ 
    		get { return _usabile_in_iter; } 
    		set { SetProperty(ref _usabile_in_iter, value); } 
    	}
    
    	private Nullable<bool> _disabilitato;
    	public Nullable<bool> disabilitato 
    	{ 
    		get { return _disabilitato; } 
    		set { SetProperty(ref _disabilitato, value); } 
    	}
    
    	#endregion
    
    
    	#region navigation
    
    	public virtual ICollection<iter_in_opere> iter_in_opere { get; set; }
    
    	#endregion
    }
}
