//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.iter_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
     
    // This class is just for meta attributes editing
    // Do not write any logic here, it will be not considered
    // Copy this class somewhere else this one will be overridden!!!
    
    public class tipologie_meta
    {
    	#region properties
    
    	[Display(Name="Id")]
    	public long id { get; set;}
    
    	[Display(Name="Tipo")]
    	public string tipo { get; set;}
    
    	[Display(Name="Disp_abbrev")]
    	public string disp_abbrev { get; set;}
    
    	[Display(Name="Disposizione")]
    	public string disposizione { get; set;}
    
    	[Display(Name="Disposizione_breve")]
    	public string disposizione_breve { get; set;}
    
    	[Display(Name="Organo")]
    	public string organo { get; set;}
    
    	[Display(Name="Organo_breve")]
    	public string organo_breve { get; set;}
    
    	[Display(Name="Sezione")]
    	public string sezione { get; set;}
    
    	[Display(Name="Localita")]
    	public string localita { get; set;}
    
    	[Display(Name="Valenza")]
    	public string valenza { get; set;}
    
    	[Display(Name="Disabilitato")]
    	public Nullable<bool> disabilitato { get; set;}
    
    	#endregion
    
    	#region navigation
    
    	[Display(AutoGenerateField=false)]
    	public virtual ICollection<iter> iter { get; set; }
    
    	#endregion
    }
    
    
    // This class couple its entity and it should be use
    // for extending functionalities of Entity class
    // here can be add de-serialized complex fields
    // or other necessary logic
    // copy this class to some other place
    // changes in this place will be overridden !!!
    
    [MetadataType(typeof(tipologie_meta))]
    public partial class tipologie
    {
    	// custom implementations
    }
}
