//------------------------------------------------------------------------------
// <auto-generated>
// By: Laco
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.db.iter_new
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using xwcs.core.db;
    using xwcs.core.db.binding.attributes;
    using xwcs.core.db.model.attributes;
    
    public partial class tipologie : EntityBase
    {
    	#region ctors and defaults
    
    	public tipologie() 
    	{
    		this.iter = new HashSet<iter>();
    	}
    	
    	
    	#endregion
    
    	#region properties
    	private long _id;
    	public long id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	private string _tipo;
    	public string tipo 
    	{ 
    		get { return _tipo; } 
    		set { SetProperty(ref _tipo, value); } 
    	}
    
    	private string _disp_abbrev;
    	public string disp_abbrev 
    	{ 
    		get { return _disp_abbrev; } 
    		set { SetProperty(ref _disp_abbrev, value); } 
    	}
    
    	private string _disposizione;
    	public string disposizione 
    	{ 
    		get { return _disposizione; } 
    		set { SetProperty(ref _disposizione, value); } 
    	}
    
    	private string _disposizione_breve;
    	public string disposizione_breve 
    	{ 
    		get { return _disposizione_breve; } 
    		set { SetProperty(ref _disposizione_breve, value); } 
    	}
    
    	private string _organo;
    	public string organo 
    	{ 
    		get { return _organo; } 
    		set { SetProperty(ref _organo, value); } 
    	}
    
    	private string _organo_breve;
    	public string organo_breve 
    	{ 
    		get { return _organo_breve; } 
    		set { SetProperty(ref _organo_breve, value); } 
    	}
    
    	private string _sezione;
    	public string sezione 
    	{ 
    		get { return _sezione; } 
    		set { SetProperty(ref _sezione, value); } 
    	}
    
    	private string _localita;
    	public string localita 
    	{ 
    		get { return _localita; } 
    		set { SetProperty(ref _localita, value); } 
    	}
    
    	private string _valenza;
    	public string valenza 
    	{ 
    		get { return _valenza; } 
    		set { SetProperty(ref _valenza, value); } 
    	}
    
    	private Nullable<bool> _disabilitato;
    	public Nullable<bool> disabilitato 
    	{ 
    		get { return _disabilitato; } 
    		set { SetProperty(ref _disabilitato, value); } 
    	}
    
    	#endregion
    
    
    	#region navigation
    
    	public virtual ICollection<iter> iter { get; set; }
    
    	#endregion
    }
}
